name: Docker Build Push
description: Build and push a multi-platform image

inputs:
  context:
    required: false
    default: "."
  file:
    required: false
    default: "./Dockerfile"
  platforms:
    required: false
    default: ""
  push:
    required: false
    default: "true"
  provenance:
    required: false
    default: "false"
  sbom:
    required: false
    default: "false"
  build-args:
    required: false
    default: ""
  tags:
    required: false
    default: ""
  cache-from:
    required: false
    default: ""
  cache-to:
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: docker/build-push-action@v7.3.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        provenance: ${{ inputs.provenance }}
        sbom: ${{ inputs.sbom }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
