[package]
name = "discord-keep-alive"
description = "Keep Discord accounts online with optional presence"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
dka-presence.workspace = true
dka-gateway.workspace = true
dka-runtime.workspace = true

serde.workspace = true
thiserror.workspace = true

tokio.workspace = true
rustls.workspace = true

clap.workspace = true
figment.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
