[advisories]
yanked = "deny"
unmaintained = "all"
unsound = "all"

[licenses]
confidence-threshold = 0.8
allow = [
  "ISC",
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
