name: Docker Login
description: Log in to a container registry

inputs:
  image:
    required: false
    default: docker/login-action@v4.6.0
  registry:
    required: true
  username:
    required: true
  password:
    required: true

runs:
  using: composite
  steps:
    - uses: ${{ inputs.image }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
