name: Check

on:
  workflow_call:
    inputs:
      checkout:
        type: string
        required: true
      runs_on:
        type: string
        required: false
        default: ubuntu

jobs:
  check:
    name: Check
    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: Checkout
        uses: ${{ inputs.checkout }}

      - name: Setup Rust
        uses: ./.gitea/actions/setup-rust

      - name: Setup cargo-deny
        uses: ./.gitea/actions/setup-cargo-deny

      - name: Deny
        run: cargo deny check

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

      - name: Test
        run: cargo test --workspace --locked
