name: Check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/cache@v6.1.0
        with:
          path: ~/.rustup
          key: rustup-toolchain-${{ hashFiles('rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

      - name: Test
        run: cargo test --workspace --locked
