name: Check

on:
  workflow_call:
    inputs:
      checkout:
        type: string
        required: true
      ref:
        type: string
        required: false
        default: ""
      runs_on:
        type: string
        required: false
        default: ubuntu

jobs:
  check:
    name: Check
    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: Checkout
        uses: ${{ inputs.checkout }}
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Rust
        uses: ./.gitea/actions/setup-rust

      - name: Setup cargo-deny
        uses: ./.gitea/actions/setup-cargo-deny

      - name: Setup cargo-shear
        uses: ./.gitea/actions/setup-cargo-shear

      - name: Deny
        run: cargo deny check -D warnings --hide-inclusion-graph

      - name: Shear
        run: cargo shear --locked --deny-warnings

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

      - name: Test
        run: cargo test --workspace --locked --all-features
