name: Check

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: false
        default: ubuntu

jobs:
  check:
    name: Check
    runs-on: ${{ inputs.runs_on }}

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ./.gitea/actions/setup-rust

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

      - name: Test
        run: cargo test --workspace --locked
