[alias]
t = "test --workspace --locked"
c = "clippy --workspace --all-targets --locked -- -D warnings"
f = "fmt --all"
ck = "check --workspace --locked"
b = "build --locked"
br = "build --release --locked"
r = "run --locked"
rr = "run --release --locked"
