[package]
name = "dka-gateway"
description = "Discord gateway session client for Discord-Keep-Alive"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
dka-presence.workspace = true

serde.workspace = true
serde_json.workspace = true

anyhow.workspace = true

tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true

tracing.workspace = true
