name: Docker Buildx
description: Set up Docker Buildx

inputs:
  image:
    required: false
    default: https://github.com/docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
  buildkit-image:
    required: false
    default: docker.io/moby/buildkit:v0.32.2@sha256:28a898719c18a33f4e8000685287fa36fd0dd9560c6440227d3a732d79bb41d8
  driver-opts:
    required: false
    default: ""

outputs:
  name:
    value: ${{ steps.setup.outputs.name }}

runs:
  using: composite
  steps:
    - id: setup
      uses: ${{ inputs.image }}
      with:
        driver-opts: |
          image=${{ inputs.buildkit-image }}
          ${{ inputs.driver-opts }}
