name: Docker Buildx
description: Set up Docker Buildx

inputs:
  image:
    required: false
    default: docker/setup-buildx-action@v4.2.0
  driver-opts:
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: ${{ inputs.image }}
      with:
        driver-opts: ${{ inputs.driver-opts }}
