name: Docker Buildx
description: Set up Docker Buildx

inputs:
  image:
    required: false
    default: docker/setup-buildx-action@v4.2.0
  driver-opts:
    required: false
    default: ""

outputs:
  name:
    value: ${{ steps.setup.outputs.name }}

runs:
  using: composite
  steps:
    - id: setup
      uses: ${{ inputs.image }}
      with:
        driver-opts: ${{ inputs.driver-opts }}
